"""add created_tstamp and modified_tstamp to quotes

Revision ID: 5a26d1c19276
Revises: de0e7dc2c2eb
Create Date: 2023-12-07 15:17:32.949586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a26d1c19276'
down_revision: Union[str, None] = 'de0e7dc2c2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes') as batch_op:
        batch_op.add_column(sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes') as batch_op:
        batch_op.drop_column('modified_tstamp')
        batch_op.drop_column('created_tstamp')
    # ### end Alembic commands ###
