"""create sources table

Revision ID: 41311264f64b
Revises: 004632ca84cb
Create Date: 2023-12-25 15:27:01.179021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41311264f64b'
down_revision: Union[str, None] = '004632ca84cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_postgres_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=False),
    sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sources_pkey')),
    sa.UniqueConstraint('source_name', name=op.f('sources_source_name_uniq_key'))
    )
    # ### end Alembic commands ###


def downgrade_postgres_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    # ### end Alembic commands ###


def upgrade_sqlite_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=False),
    sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sources_pkey')),
    sa.UniqueConstraint('source_name', name=op.f('sources_source_name_uniq_key'))
    )
    # ### end Alembic commands ###


def downgrade_sqlite_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    # ### end Alembic commands ###

