"""add created_tstamp and modified_tstamp to quotes

Revision ID: 88e2ebbd8c8d
Revises: 72026ce9cd09
Create Date: 2023-12-08 23:02:21.313576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e2ebbd8c8d'
down_revision: Union[str, None] = '72026ce9cd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_postgres_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('quotes', sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade_postgres_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'modified_tstamp')
    op.drop_column('quotes', 'created_tstamp')
    # ### end Alembic commands ###


def upgrade_sqlite_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes') as batch_op:
        batch_op.add_column(sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade_sqlite_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes') as batch_op:
        batch_op.drop_column('modified_tstamp')
        batch_op.drop_column('created_tstamp')
    # ### end Alembic commands ###

